language: android

android:
  components:
  - tools
  - build-tools-28.0.3
  - android-28
  - platform-tools
  - extra-android-support
  - extra-android-m2repositor
  - extra-google-google_play_servicesy
  - extra-google-m2repository
  licenses:
  - android-sdk-license-.+

sudo: required

jdk:
- oraclejdk8

script:
  - ./gradlew clean build test ktlint

#jobs:
#  include:
#    - stage: build
#      script: ./gradlew clean build
#
#    - stage: test
#      script: ./gradlew test
#
#    - stage: lint check
#      script: ./gradlew ktlint