language: android

android:
  components:
  - tools
  - build-tools-28.0.3
  - android-28
  - android-22
  - platform-tools
  - extra-android-support
  - extra-android-m2repositor
  - extra-google-google_play_servicesy
  - extra-google-m2repository
  - sys-img-armeabi-v7a-android-22
  licenses:
  - android-sdk-license-.+

sudo: required

jdk:
- oraclejdk8

jobs:
  include:
  - stage: build
    script: ./gradlew clean build -PnoLint -x test -x detekt

  - stage: test
    script: ./gradlew test

  - stage: lint checks
    script: ./gradlew ktlint detekt

  - stage: ui test
    if: branch == master
    script:
    # Emulator Management: Create, Start and Wait
    - echo no | android create avd --force -n test -t android-22 --abi armeabi-v7a -c 100M
    - emulator -avd test -no-audio -no-window &
    - android-wait-for-emulator
    - adb shell input keyevent 82 &
    - ./gradlew cAT